# Use the Ruby 3.2.2 image from Docker Hub as the base image (https://hub.docker.com/_/ruby)
FROM ruby:3.2.2

RUN ls /etc
RUN apt update -qq && apt install -y postgresql-client git libvips curl cron vim
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt install nodejs
RUN npm install --global yarn
RUN mkdir -p /data/typesense

WORKDIR /app

ARG DATABASE_HOST
ARG DATABASE_NAME
ARG DATABASE_PORT
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
ARG HOSTNAME
ARG TYPESENSE_API_KEY
ARG RAILS_ENV
ARG REACT_APP_IIIF_MANIFEST_ITEM_LIMIT
ARG REACT_APP_MAP_TILER_KEY
ARG REACT_APP_IIIF_MANIFEST_ITEM_LIMIT
ARG IIIF_CLOUD_PROJECT_ID
ARG IIIF_CLOUD_API_KEY
ARG IIIF_CLOUD_URL
ARG SECRET_KEY_BASE
ARG AUTHENTICATION_EXPIRATION
ARG TYPESENSE_SEARCH_KEY

# Add Rails gems
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock
COPY crontab /var/spool/cron/crontabs/root

RUN bundle install

RUN curl -O https://dl.typesense.org/releases/26.0/typesense-server-26.0-linux-amd64.tar.gz && \
  tar -xzf typesense-server-26.0-linux-amd64.tar.gz

COPY . .

RUN sed -i -e 's|api-key.*|'"api-key = $TYPESENSE_API_KEY"'|g' ./typesense-server.ini
RUN sed -i -e 's|TYPESENSE_API_KEY|'"$TYPESENSE_API_KEY"'|g' ./update.sh

ENV AUTHENTICATION_EXPIRATION=$AUTHENTICATION_EXPIRATION
ENV GENERATE_SOURCEMAP=false
ENV DATABASE_HOST=$DATABASE_HOST
ENV DATABASE_NAME=$DATABASE_NAME
ENV DATABASE_PORT=$DATABASE_PORT
ENV DATABASE_USERNAME=$DATABASE_USERNAME
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV DISABLE_ESLINT_PLUGIN=true
ENV HOSTNAME=$HOSTNAME
ENV IIIF_CLOUD_PROJECT_ID=$IIIF_CLOUD_PROJECT_ID
ENV IIIF_CLOUD_API_KEY=$IIIF_CLOUD_API_KEY
ENV IIIF_CLOUD_URL=$IIIF_CLOUD_URL
ENV NODE_OPTIONS="--max-old-space-size=16384"
ENV RAILS_MAX_THREADS=5
ENV RAILS_ENV=development
ENV REACT_APP_HOSTNAME=$HOSTNAME
ENV REACT_APP_IIIF_MANIFEST_ITEM_LIMIT=$REACT_APP_IIIF_MANIFEST_ITEM_LIMIT
ENV REACT_APP_IIIF_MANIFEST_ITEM_LIMIT=$REACT_APP_IIIF_MANIFEST_ITEM_LIMIT
ENV REACT_APP_MAP_TILER_KEY=$REACT_APP_MAP_TILER_KEY
ENV SECRET_KEY_BASE=$SECRET_KEY_BASE
ENV TYPESENSE_API_KEY=$TYPESENSE_API_KEY
ENV TYPESENSE_SEARCH_KEY=$TYPESENSE_SEARCH_KEY

# Build and deploy React front-end
RUN yarn config set network-timeout 600000 -g
RUN yarn build && yarn deploy

# Clean up APT when done.
RUN apt clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN chmod +x ./ecds-entrypoint.sh
RUN chmod +x ./update.sh

EXPOSE 3000 8108

ENTRYPOINT [ "./ecds-entrypoint.sh" ]